config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :rooms do
    resources :events
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
  
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_room 
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @events = Event.scoped
    @events = Event.between(params['start'], params['end']) if (params['start'] && params['end'])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @events }
    end
  end

  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event }
    end
  end

  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @event }
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    if check_date
      respond_to do |format|
        if @event.save
          format.html { redirect_to room_event_path(@room, @event), :notice => 'Event was successfully created.' }
          format.json { render :json => @event, :status => :created, :location => @event }
        else
          format.html { render :action => "new" }
          format.json { render :json => @event.errors, :status => :unprocessable_entity }
        end
      end
    else
      render :new
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, :notice => 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to room_path(@room) }
      format.json { head :no_content }
    end
  end

  private 
  def event_params
    params.require(:event).permit(:title, :starts_at, :ends_at, :all_day, :description, :user_id, :room_id)
  end

  def find_room
    @room = Room.find(params[:room_id])
  end

  def check_date
    if @room.events.where(['starts_at BETWEEN ? AND ?', @event.starts_at, @event.ends_at]).any?
      # conflict with start time
      return false
    elsif @room.events.where(['ends_at BETWEEN ? AND ?', @event.starts_at, @event.ends_at]).any?
      # conflic with 'end' time
      return false
  	else
    	return true
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  	@rooms = Room.all
  end

  def show
  	@room = Room.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/events/_form.html.erb
<%= form_for [@room, @event] do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Title' %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <input type="date" class="datepicker" name='event[starts_at]'/>
  </div>
  <div class="field">
    <%= f.label :starts_at %><br />
    <%= f.text_field :starts_at %>
  </div>
  <div class="field">
    <%= f.label :ends_at %><br />
    <%= f.text_field :ends_at %>
  <div class="field">
    <%= f.label :all_day %><br />
    <%= f.check_box :all_day %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <%= f.hidden_field :room_id, :value => @room.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Back to Event', room_event_path(@room, @event) %> |
<%= link_to 'Back to Room', room_path(@room) %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Starts at</th>
    <th>Ends at</th>
    <th>All day</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @room.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.starts_at %></td>
    <td><%= event.ends_at %></td>
    <td><%= event.all_day %></td>
    <td><%= event.description %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_room_event_path(@room, event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_room_event_path(@room) %>
<%= link_to 'Home', root_path %>

app/views/events/new.html.erb
<h1>Schedule Event</h1>

<%= render 'form' %>

<%= link_to 'Back to Room', room_path(@room) %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @event.title %></h1>
<hr />
<p>
  <b>Starts at:</b>
  <%= @event.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%= @event.ends_at %>
</p>

<% if @event.all_day %>
  <p>
    <b>All day:</b>
    <%= @event.all_day %>
  </p>
<% end %>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>


<%= link_to 'Edit Event', edit_room_event_path(@room, @event) %> |
<%= link_to 'Cancel Event', room_event_path(@room, @event), method: :delete, data: {confirm: 'Do you really want to cancel this event?'} %> |
<%= link_to 'Back to Room Schedule', room_path(@room) %>

app/views/home/index.html.erb
<h1 class='text-align center'>Church & State</h1>
<br />
<div id="calendar">
</div>

app/views/layouts/_nav_bar.html.erb
<div class="black-text">
  <div class='row'>
    <div class=' col s3 center-align'>
    <%= link_to "Home", root_path %>
    </div>
    <div class=' col s3 center-align'>
    <%= link_to "Sign In", new_user_session_path %>
    </div>
    <div class=' col s3 center-align'>
    <%= link_to "Log Out", destroy_user_session_path,method: :delete %>
    </div>
    <div class=' col s3 center-align'>
    <%= link_to "Conference Rooms", rooms_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CnsScheduler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= render 'layouts/nav_bar'%>

<div class='container'>
<%= yield %>
</div>

</body>
</html>

app/views/rooms/index.html.erb
<h1>Rooms</h1>
<ul>
  <% @rooms.each do |room| %>
  <li>
    <h3><%= link_to room.name, room_path(room) %></h3>
    <h4>Room Capacity:<%= room.capacity %></h4>
    <h4>Description<%= room.description %></h4>
  </li>
  <% end %>
</ul>

app/views/rooms/show.html.erb
<h1><%= @room.name %></h1>
<h4>Room Capacity: <%= @room.capacity %></h4>
<h4>Description: <%= @room.description %></h4>
<br />

<h3>Scheduled Events</h3>
<ul>
  <% @room.events.each do |event| %>
    <li>
      <%= link_to event.title, room_event_path(@room, event) %>
      <br/>
      Starts at: <%= event.starts_at %>
      <br/>
      Ends at: <%= event.ends_at %>
    </li>
    <hr />
  <% end %>
</ul>
<%= link_to 'Create Event', new_room_event_path(@room) %> |
<%= link_to 'Back to Rooms', rooms_path %>